---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd

platforms:
  - name: debian-9
  - name: ubuntu-18.04
  - name: centos-7

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: firewalld
  salt_copy_filter:
    - .kitchen
    - .git
  pillars:
    top.sls:
      base:
        '*':
          - firewalld
    firewalld.sls:
      firewalld:
        enabled: True
        services:
          glusterfs:
            short: glusterfs
            description: 'GlusterFS network filesystem'
            ports:
              tcp:
                - 24007-24008
                - 49152-49200

verifier:
  name: inspec
  sudo: false
  # cli, documentation, html, progress, json, json-min, json-rspec, junit
  reporter: cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - firewalld
